const PDFParser = require("pdf2json");
const { GoogleGenAI, Type } = require('@google/genai');
const Analysis = require('../models/Analysis');

// Initialize Gemini SDK with your environment API Key
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

/**
 * @desc    Upload a resume PDF, parse text using pdf2json, analyze using Gemini AI, and save results
 * @route   POST /api/resume/analyze
 */
exports.analyzeResume = async (req, res) => {
    try {
        const { jobDescription } = req.body;
        
        // Input Validation Guardrails
        if (!req.file) {
            return res.status(400).json({ error: 'Please upload a resume PDF file.' });
        }
        if (!jobDescription || jobDescription.trim() === "") {
            return res.status(400).json({ error: 'Please provide a target job description.' });
        }

        // 2. Parse PDF binary text straight from memory buffer using pdf2json
        let resumeText = '';
        try {
            resumeText = await new Promise((resolve, reject) => {
                const pdfParser = new PDFParser(null, 1); // '1' flag extracts raw text directly

                pdfParser.on("pdfParser_dataError", errData => reject(errData.parserError));
                pdfParser.on("pdfParser_dataReady", pdfData => {
                    // Extract and decode the raw text fields from the parsed map
                    const rawText = pdfParser.getRawTextContent();
                    resolve(rawText);
                });

                // Feed the multer file memory buffer directly into the parser
                pdfParser.parseBuffer(req.file.buffer);
            });

            // Clean up messy spacing/line breaks generated by PDF readers
            resumeText = resumeText.replace(/\s+/g, ' ').trim();

            // Final check: If it's still empty, it's a flat scanned image file
            if (!resumeText || resumeText.length < 10) {
                return res.status(422).json({ 
                    error: 'The uploaded PDF contains no selectable text data. If this is a scanned document, please use a document exported directly from Google Docs, Word, or Canva instead.' 
                });
            }

        } catch (pdfError) {
            console.error('PDF Processing Engine Exception:', pdfError);
            return res.status(422).json({ error: 'Failed to read file layout framework. Ensure it is a valid, uncorrupted PDF document.' });
        }

        // 3. Construct optimization instructions for Gemini
        const prompt = `
            You are an expert ATS (Applicant Tracking System) optimization tool.
            Analyze the following resume text against the provided job description.
            
            Resume Text:
            "${resumeText}"
            
            Job Description:
            "${jobDescription}"
        `;

        // 4. Fire Request to Gemini using structural JSON configuration constraints
        let response;
        try {
            response = await ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: prompt,
                config: {
                    responseMimeType: 'application/json',
                    responseSchema: {
                        type: Type.OBJECT,
                        properties: {
                            atsScore: { type: Type.INTEGER, description: 'Score from 0 to 100 based on alignment' },
                            matchedKeywords: { type: Type.ARRAY, items: { type: Type.STRING } },
                            missingKeywords: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Important technical or soft skills missing' },
                            suggestions: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Actionable improvements for resume bullet points' }
                        },
                        required: ['atsScore', 'matchedKeywords', 'missingKeywords', 'suggestions']
                    }
                }
            });
        } catch (aiError) {
            console.error('Gemini API Communication Error:', aiError);
            return res.status(502).json({ error: 'Failed to communicate with AI generation backend ecosystem.' });
        }

        // 5. Safely handle JSON Parsing exceptions from Network Layer
        let aiData;
        try {
            aiData = JSON.parse(response.text);
        } catch (parseError) {
            console.error('Gemini structural formatting exception output:', response.text);
            return res.status(502).json({ error: 'AI generated an unparsable response framework structure.' });
        }

        // 6. Map and sanitize fallback payloads to guarantee DB scheme compliance
        const analysisLog = new Analysis({
            filename: req.file.originalname,
            jobDescription: jobDescription.trim(),
            atsScore: typeof aiData.atsScore === 'number' ? aiData.atsScore : 0,
            matchedKeywords: Array.isArray(aiData.matchedKeywords) ? aiData.matchedKeywords : [],
            missingKeywords: Array.isArray(aiData.missingKeywords) ? aiData.missingKeywords : [],
            suggestions: Array.isArray(aiData.suggestions) ? aiData.suggestions : []
        });

        // 7. Persist document payload inside MongoDB
        await analysisLog.save();

        // 8. Return response directly to front-end handler
        return res.status(200).json(analysisLog);

    } catch (globalError) {
        console.error('Critical Analysis Failure:', globalError);
        return res.status(500).json({ error: 'Internal Server Error encountered during core processing pipelines.' });
    }
};

/**
 * @desc    Fetch historical scan analytics sessions
 * @route   GET /api/resume/history
 */
exports.getHistory = async (req, res) => {
    try {
        const history = await Analysis.find().sort({ createdAt: -1 });
        return res.status(200).json(history);
    } catch (error) {
        console.error('History Query Exception:', error);
        return res.status(500).json({ error: 'Failed to retrieve analysis logs directory.' });
    }
};

/**
 * @desc    Remove historical analysis metrics node
 * @route   DELETE /api/resume/:id
 */
exports.deleteAnalysis = async (req, res) => {
    try {
        const { id } = req.params;
        const targetRecord = await Analysis.findByIdAndDelete(id);

        if (!targetRecord) {
            return res.status(404).json({ error: 'The specified analysis history record could not be found.' });
        }

        return res.status(200).json({ message: 'Analysis record wiped successfully.' });
    } catch (error) {
        console.error('Delete Route Exception:', error);
        return res.status(500).json({ error: 'Failed to process document purge event command.' });
    }
};